### ISSUE TITLE
state is not defined in alerts 

### ISSUE THREAD

**Issue by skorasaurus** [kyle-jennings/franklin#1]
Hi, 

First off, thanks for making this and benjamin. This has been really helpful as I'm relearning CSS and how to integrate USDS in a wordpress environment. 

I implemented franklin for the first time and received an error on a page: 

` Undefined variable: state in PATH/wp-content/plugins/franklin/inc/shortcodes/alerts.php on line 16

Notice: Undefined variable: size in PATH/wp-content/plugins/franklin/inc/shortcodes/alerts.php on line 18`

I should note that the alert still displays as intended.

**Comment by skorasaurus** [comment]
Oh god, I did I not realize this error; it's just that the variable haven't been defined yet and I had wp_debug set to true;

**Comment by kyle-jennings** [comment]
no no thanks for pointing that out, I've been neglecting both this plugin and the theme and plan on pushing some much needed updates and bug fixes soon.

Ideally, there should be some fail safes built in to avoid these notices, but I write this plugin really quickly.

**Comment by kyle-jennings** [comment]
This is fixed BTW @skorasaurus
